apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: react-app
  namespace: default
spec:
  interval: 5m
  releaseName: react-app
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: react-chart
        namespace: flux-system
  reconcileStrategy: Revision
  values:
    image:
      repository: ghcr.io/chau-nm/react-helm-example
      tag: latest
    service:
      type: ClusterIP
      port: 80